[tool.poetry]
name = "site"
version = "0.0.1"
description = "A webserver application for managing and interacting with our modmail bot."
authors = [
    "aru <genericusername414@gmail.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.7.0"
coloredlogs = "^15.0"
jinja2 = "^3.0.1"
pydantic = "^1.8.2"
python-dotenv = "^0.17.1"
starlette = "^0.14.2"
toml = "^0.10.2"
uvicorn = {extras = ["standard"], version = "^0.13.4"}

[tool.poetry.extras]
uvicorn = ["standard"]

[tool.poetry.dev-dependencies]
black = "~=21.5b1"
flake8 = "~=3.8"
flake8-annotations = "~=2.3"
flake8-bugbear = "~=20.1"
flake8-docstrings = "~=1.5"
flake8-import-order = "~=0.18"
flake8-string-format = "~=0.3"
flake8-tidy-imports = "~=4.1"
flake8-todo = "~=0.7"
pep8-naming = "~=0.11"
pre-commit = "~=2.1"
taskipy = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "uvicorn main:app"
debug = "uvicorn main:app --reload"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
black = "black --check ."
flake8 = "python -m flake8"

[tool.black]
line-length = 99
target-version = ['py38']
include = '\.pyi?$'
